#  scikit-Learn presents a that implements a sing TLU (Threshold Logic Unit) network.

# TASK 1
# Use a perceptron classifier to predict whether a given iris flower 
# is of the species Iris setosa based on its petal length and petal width. 

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

# Perceptron from sklearn.linear_model for the perceptron classifier
#  load_iris from sklearn.datasets to load the Iris dataset.
iris = load_iris()

print(iris.data[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [2]:
# You assigned x to be the petal length and petal width, which are the 3rd and 4th features (indexing starts from 0) of the Iris dataset.
x = iris.data[:,(2,3)] # petal length, petal width

# You created the target variable y by checking if the target corresponds to Iris Setosa. 
# If it is, it's labeled as 1; otherwise, it's labeled as 0.
y = (iris.target == 0).astype(int) # Iris setosa?

# You instantiated a Perceptron classifier.
# You trained the perceptron classifier (per_clf) using the fit() method with x and y. 
per_clf = Perceptron()
per_clf.fit(x,y)

# You predicted the class of a new sample [2, 0.5] using the predict() method.
y_pred = per_clf.predict([[2,0.5]])

print("Predicted class:", y_pred)

Predicted class: [0]


In [3]:
import tensorflow as tf
from tensorflow import keras

print(tf.__version__)


2024-04-26 02:49:51.955451: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-26 02:49:51.964947: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-26 02:49:52.161747: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-26 02:49:54.656904: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


2.16.1


# Building an image classifier using the sequential API

In [4]:
# using keras to load the dataset
fashion_mnist = keras.datasets.fashion_mnist

(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()

#  when loading with using keras instead of Scikit-Learn, remember that 
# every image is represented as 28x28 array rather a 1D array of size 784.


In [5]:
# moreover, the pixel intensitiesd are inetgers (0 to 255) 
#  instead of float (0.0 to 255.0)


In [6]:
# looking at the shape and data type of trfaining set

print(X_train_full.shape)

(60000, 28, 28)


In [7]:
print(X_train_full.dtype)

uint8


#  Data set is split into training and test set  but no validation set. Let's create one

# Since we're going to train the NN using gradient descent, we must scale the input features. For simpliicity we scalle down to 0-1 range by dividing them by 255.0

In [8]:
X_valid, X_train = X_train_full[:5000]/255.0, X_train_full[5000:]/255.0

y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

In [9]:
#  For MNIST, when the lable is equal to 5, it means the iamge represents the handwritten 5. Easy.
# For fashion MNIST, we need the list of class names to know what we are dealing with:
# Example:

class_names = ["T-shirts/top","Trouser","Pullover","Dress","Coat", "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

In [10]:
# For example the first bimage in the training set represents a coat
print(class_names[y_train[0]])

Coat


In [11]:
#  Creating the model usibng sequential API

model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28]))
model.add(keras.layers.Dense(300, activation = "relu"))
model.add(keras.layers.Dense(100, activation = "relu"))
model.add(keras.layers.Dense(10, activation = "softmax"))




/home/student/.local/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [12]:
# instead of adding the layers one by one as we did,
#  you can just pass a list of layers when creating the Sequential model

model = keras.models.Sequential([
    
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.Dense(300, activation = "relu"),
    keras.layers.Dense(100, activation = "relu"),
    keras.layers.Dense(10, activation = "softmax")
    
    ])

the models summary() method displays all the model's layers, including each layer's name (which is autom,atically generated unless you set it ehrn creating the layer).... The summary ends with the total numbwer of parameters including trainable and non-trainable parameters.

In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_1 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 266,610 (1.02 MB)

 Trainable params: 266,610 (1.02 MB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# You can easily get a model's lsit of layers, to fetch a laer by it's index or by it's name

model.layers

[<Flatten name=flatten_1, built=True>,
 <Dense name=dense_3, built=True>,
 <Dense name=dense_4, built=True>,
 <Dense name=dense_5, built=True>]

In [15]:
hidden1 = model.layers[1]
hidden1.name

'dense_3'

In [16]:
model.get_layer('dense_3') is hidden1


True

In [17]:
# All parameters of a layer can be accessed using its get_weights() and set_weights() methods
#  For a Dense layer, this includes both the connection weights and the bias terms

weights, biases = hidden1.get_weights()
weights

array([[ 0.01918815, -0.02789132,  0.05091231, ...,  0.00318364,
         0.0681819 , -0.02836049],
       [-0.04527554,  0.06444542, -0.06854466, ...,  0.03760485,
        -0.053754  , -0.032523  ],
       [-0.03920981, -0.06553729,  0.06869903, ..., -0.02553987,
         0.06113097, -0.03916094],
       ...,
       [ 0.01775181,  0.0370803 , -0.05799056, ...,  0.05962604,
        -0.01531805,  0.03638051],
       [ 0.00012026,  0.0234767 ,  0.01268665, ..., -0.06842616,
        -0.06820598,  0.04970134],
       [ 0.05427918, -0.06398501,  0.03681192, ..., -0.01882217,
         0.02465776,  0.05234049]], dtype=float32)

In [18]:
weights.shape

(784, 300)

In [19]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [20]:
biases.shape

(300,)

In [21]:
# Compiling the model
#  You mus cal its compile () method to specify the loss func and optimizer to use

model.compile(loss="sparse_categorical_crossentropy",
             optimizer = "sgd",
             metrics = ["accuracy"])

In [ ]:
#  Training the model
#  The model is ready to be trained. For this we simply need to call its fit() method:


history =  model.fit(X_train, y_train, epochs = 30,
                    validation_data = (X_valid, y_valid))




Epoch 1/30


2024-04-26 02:49:58.766111: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 172480000 exceeds 10% of free system memory.


1719/1719 ━━━━━━━━━━━━━━━━━━━━ 18s 10ms/step - accuracy: 0.6814 - loss: 0.9859 - val_accuracy: 0.8332 - val_loss: 0.5013
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 19s 9ms/step - accuracy: 0.8266 - loss: 0.4987 - val_accuracy: 0.8270 - val_loss: 0.4767
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 21s 9ms/step - accuracy: 0.8452 - loss: 0.4445 - val_accuracy: 0.8540 - val_loss: 0.4244
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 18s 8ms/step - accuracy: 0.8557 - loss: 0.4149 - val_accuracy: 0.8680 - val_loss: 0.3871
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - accuracy: 0.8634 - loss: 0.3910 - val_accuracy: 0.8626 - val_loss: 0.3937
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.8677 - loss: 0.3781 - val_accuracy: 0.8678 - val_loss: 0.3817
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.8703 - loss: 0.3651 - val_accuracy: 0.8712 - val_loss: 0.3726
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - accuracy: 0.8758 - loss: 0.3530 - va

In [ ]:
# learning curve 

import pandas as pd
import matplotlib.pyplot as plt

# Assuming history is a variable containing the training history of your model

# Creating a DataFrame from the training history and plotting
pd.DataFrame(history.history).plot(figsize=(8,5))
plt.grid(True)
plt.gca().set_ylim(0,1) # set the vertical range to [0-1]
plt.show()
